name = "tetik-pinger"
main = "src/index.js"
compatibility_date = "2026-01-01"

# Анти-пауза Supabase + дубль автомодерации, каждые 6 часов
[triggers]
crons = ["0 */6 * * *"]

[vars]
SUPABASE_URL = "https://yugknlsapjcuelegbfpt.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1Z2tubHNhcGpjdWVsZWdiZnB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ5MDUzNzcsImV4cCI6MjEwMDQ4MTM3N30.u5BLA_4eGVmMKC0gaN1QiXrQBqNjtKGiwXkC6BEE2vE"
